export const APP_NAME = 'Psssssssst'

export const DEFAULT_AVATAR = 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTh0tJhJWjd5dacn4jpGOtqtCs-qvW5u4xGYg&usqp=CAU'

export const DEFAULT_NICKNAME = 'hiro942'

// 邮箱格式
export const EmailRegExp = /^[a-zA-z\d._-]+@[a-zA-z\d]+.[a-zA-z\d]+/

// 密码为字母（大小写均可）和数字的组合
export const PasswordRegExp = /[a-zA-z\d]+/

// 昵称为任意表意文字
export const NameRegExp = /[\p{Unified_Ideograph}a-zA-Z\d]+/u

// 别名配置
export const AliasCN: any = {
  assigner: '创建人',
  assignDateTime: '创建时间',
  createTime: '创建时间',

  taskID: '任务ID',
  taskName: '任务名称',
  modelID: '模型ID',
  modelName: '模型名称',

  currentNumber: '当前节点数',
  numberOfPeers: '参与节点数',
  peersRatio: '参与方',

  state: '任务状态',
  timeLimit: '任务开始时间',
  description: '任务描述',

  // partition: '文件分块',

  trainFile: '训练数据文件',
  evaluateFile: '测试数据文件',

  nickname: '用户名',
  partyID: '组织ID',
  participateDateTime: '参与时间',

  ASSIGNED: { text: '待开始', type: 'info' },
  TRAINED: { text: '进行中', type: 'danger' },
  FINISHED: { text: '已完成', type: 'success' },
}

export const modelInfoTest = {
  anonymousNameMapping: {},
  bestIteration: -1,
  classes: ['0', '1'],
  featureImportances: [
    {
      fid: 18,
      fullname: 'x18',
      importance: 5.0,
      importance2: 3179.525225857,
      main: 'split',
      sitename: 'guest',
    },
    {
      fid: 19,
      fullname: 'x19',
      importance: 2.0,
      importance2: 509.8697233143,
      main: 'split',
      sitename: 'guest',
    },
    {
      fid: 20,
      fullname: 'x20',
      importance: 2.0,
      importance2: 101.2239560645,
      main: 'split',
      sitename: 'guest',
    },
    {
      fid: 13,
      fullname: 'x13',
      importance: 2.0,
      importance2: 76.8044301222,
      main: 'split',
      sitename: 'guest',
    },
    {
      fid: 7,
      fullname: 'x7',
      importance: 2.0,
      importance2: 65.9686476161,
      main: 'split',
      sitename: 'guest',
    },
    {
      fid: 10,
      fullname: 'x10',
      importance: 2.0,
      importance2: 47.5646125887,
      main: 'split',
      sitename: 'guest',
    },
    {
      fid: 9,
      fullname: 'x9',
      importance: 1.0,
      importance2: 90.3291961282,
      main: 'split',
      sitename: 'guest',
    },
    {
      fid: 15,
      fullname: 'x15',
      importance: 1.0,
      importance2: 24.5968602849,
      main: 'split',
      sitename: 'guest',
    },
    {
      fid: 22,
      fullname: 'x22',
      importance: 1.0,
      importance2: 76.722886152,
      main: 'split',
      sitename: 'guest',
    },
    {
      fid: 14,
      fullname: 'x14',
      importance: 1.0,
      importance2: 14.5427269078,
      main: 'split',
      sitename: 'guest',
    },
    {
      fid: 21,
      fullname: 'x21',
      importance: 1.0,
      importance2: 44.611955692,
      main: 'split',
      sitename: 'guest',
    },
    {
      fid: 0,
      fullname: 'x0',
      importance: 1.0,
      importance2: 19.3185476696,
      main: 'split',
      sitename: 'guest',
    },
  ],
  featureNameFidMapping: {
    0: 'x0',
    1: 'x1',
    10: 'x10',
    11: 'x11',
    12: 'x12',
    13: 'x13',
    14: 'x14',
    15: 'x15',
    16: 'x16',
    17: 'x17',
    18: 'x18',
    19: 'x19',
    2: 'x2',
    20: 'x20',
    21: 'x21',
    22: 'x22',
    3: 'x3',
    4: 'x4',
    5: 'x5',
    6: 'x6',
    7: 'x7',
    8: 'x8',
    9: 'x9',
  },
  initScore: [0.0],
  losses: [],
  modelName: 'homo_sbt',
  numClasses: 2,
  treeDim: 1,
  treeNum: 3,
  treePlan: [],
  trees: [
    {
      missingDirMaskdict: {},
      splitMaskdict: {},
      tree: [
        {
          bid: 0.9047122646969068,
          fid: 18,
          id: 0,
          isLeaf: false,
          leftNodeid: 1,
          missingDir: 1,
          rightNodeid: 2,
          sitename: 'guest',
          weight: -1.1099722507,
        },
        {
          bid: 1.573512813942988,
          fid: 19,
          id: 1,
          isLeaf: false,
          leftNodeid: 3,
          missingDir: 1,
          rightNodeid: 4,
          sitename: 'guest',
          weight: -1.3279807531,
        },
        {
          bid: -0.695773484744511,
          fid: 20,
          id: 2,
          isLeaf: false,
          leftNodeid: 5,
          missingDir: 1,
          rightNodeid: 6,
          sitename: 'guest',
          weight: 0.7213345864,
        },
        {
          bid: -0.29680099894987155,
          fid: 9,
          id: 3,
          isLeaf: false,
          leftNodeid: 7,
          missingDir: 1,
          rightNodeid: 8,
          sitename: 'guest',
          weight: -1.4333404797,
        },
        {
          bid: 1.4789320866372022,
          fid: 13,
          id: 4,
          isLeaf: false,
          leftNodeid: 9,
          missingDir: 1,
          rightNodeid: 10,
          sitename: 'guest',
          weight: -0.2164082688,
        },
        {
          bid: -0.34194199889079346,
          fid: 7,
          id: 5,
          isLeaf: false,
          leftNodeid: 11,
          missingDir: 1,
          rightNodeid: 12,
          sitename: 'guest',
          weight: -0.3619909503,
        },
        {
          bid: 1.452967081295793,
          fid: 15,
          id: 6,
          isLeaf: false,
          leftNodeid: 13,
          missingDir: 1,
          rightNodeid: 14,
          sitename: 'guest',
          weight: 0.7804757185,
        },
        {
          bid: 0.0,
          fid: 0,
          id: 7,
          isLeaf: true,
          leftNodeid: -1,
          missingDir: 1,
          rightNodeid: -1,
          sitename: 'guest',
          weight: -1.0811263829,
        },
        {
          bid: 0.0,
          fid: 0,
          id: 8,
          isLeaf: true,
          leftNodeid: -1,
          missingDir: 1,
          rightNodeid: -1,
          sitename: 'guest',
          weight: -1.5120287792,
        },
        {
          bid: 0.0,
          fid: 0,
          id: 9,
          isLeaf: true,
          leftNodeid: -1,
          missingDir: 1,
          rightNodeid: -1,
          sitename: 'guest',
          weight: -0.1517194876,
        },
        {
          bid: 0.0,
          fid: 0,
          id: 10,
          isLeaf: true,
          leftNodeid: -1,
          missingDir: 1,
          rightNodeid: -1,
          sitename: 'guest',
          weight: -1.679389313,
        },
        {
          bid: 0.0,
          fid: 0,
          id: 11,
          isLeaf: true,
          leftNodeid: -1,
          missingDir: 1,
          rightNodeid: -1,
          sitename: 'guest',
          weight: 0.5940594059,
        },
        {
          bid: 0.0,
          fid: 0,
          id: 12,
          isLeaf: true,
          leftNodeid: -1,
          missingDir: 1,
          rightNodeid: -1,
          sitename: 'guest',
          weight: -1.1570247934,
        },
        {
          bid: 0.0,
          fid: 0,
          id: 13,
          isLeaf: true,
          leftNodeid: -1,
          missingDir: 1,
          rightNodeid: -1,
          sitename: 'guest',
          weight: 0.8068153345,
        },
        {
          bid: 0.0,
          fid: 0,
          id: 14,
          isLeaf: true,
          leftNodeid: -1,
          missingDir: 1,
          rightNodeid: -1,
          sitename: 'guest',
          weight: -1.5217391305,
        },
      ],
    },
    {
      missingDirMaskdict: {},
      splitMaskdict: {},
      tree: [
        {
          bid: 0.01490308034690498,
          fid: 18,
          id: 0,
          isLeaf: false,
          leftNodeid: 1,
          missingDir: 1,
          rightNodeid: 2,
          sitename: 'guest',
          weight: -0.8141103752,
        },
        {
          bid: 0.23495892683718056,
          fid: 22,
          id: 1,
          isLeaf: false,
          leftNodeid: 3,
          missingDir: 1,
          rightNodeid: 4,
          sitename: 'guest',
          weight: -1.0784433969,
        },
        {
          bid: 0.9047122646969068,
          fid: 18,
          id: 2,
          isLeaf: false,
          leftNodeid: 5,
          missingDir: 1,
          rightNodeid: 6,
          sitename: 'guest',
          weight: 0.0379696666,
        },
        {
          bid: -0.8284113775077981,
          fid: 13,
          id: 3,
          isLeaf: false,
          leftNodeid: 7,
          missingDir: 1,
          rightNodeid: 8,
          sitename: 'guest',
          weight: -1.1130972789,
        },
        {
          bid: -1.2343229989289584,
          fid: 14,
          id: 4,
          isLeaf: false,
          leftNodeid: 9,
          missingDir: 1,
          rightNodeid: 10,
          sitename: 'guest',
          weight: -0.3235771388,
        },
        {
          bid: 0.18878682528213997,
          fid: 21,
          id: 5,
          isLeaf: false,
          leftNodeid: 11,
          missingDir: 1,
          rightNodeid: 12,
          sitename: 'guest',
          weight: -0.367761811,
        },
        {
          bid: 0.2531789084829441,
          fid: 0,
          id: 6,
          isLeaf: false,
          leftNodeid: 13,
          missingDir: 1,
          rightNodeid: 14,
          sitename: 'guest',
          weight: 0.5135569373,
        },
        {
          bid: 0.0,
          fid: 0,
          id: 7,
          isLeaf: true,
          leftNodeid: -1,
          missingDir: 1,
          rightNodeid: -1,
          sitename: 'guest',
          weight: -0.8848689007,
        },
        {
          bid: 0.0,
          fid: 0,
          id: 8,
          isLeaf: true,
          leftNodeid: -1,
          missingDir: 1,
          rightNodeid: -1,
          sitename: 'guest',
          weight: -1.1874930898,
        },
        {
          bid: 0.0,
          fid: 0,
          id: 9,
          isLeaf: true,
          leftNodeid: -1,
          missingDir: 1,
          rightNodeid: -1,
          sitename: 'guest',
          weight: 0.0715876164,
        },
        {
          bid: 0.0,
          fid: 0,
          id: 10,
          isLeaf: true,
          leftNodeid: -1,
          missingDir: 1,
          rightNodeid: -1,
          sitename: 'guest',
          weight: -0.6089198436,
        },
        {
          bid: 0.0,
          fid: 0,
          id: 11,
          isLeaf: true,
          leftNodeid: -1,
          missingDir: 1,
          rightNodeid: -1,
          sitename: 'guest',
          weight: -0.5301045938,
        },
        {
          bid: 0.0,
          fid: 0,
          id: 12,
          isLeaf: true,
          leftNodeid: -1,
          missingDir: 1,
          rightNodeid: -1,
          sitename: 'guest',
          weight: 0.1914126094,
        },
        {
          bid: 0.0,
          fid: 0,
          id: 13,
          isLeaf: true,
          leftNodeid: -1,
          missingDir: 1,
          rightNodeid: -1,
          sitename: 'guest',
          weight: 0.3315875605,
        },
        {
          bid: 0.0,
          fid: 0,
          id: 14,
          isLeaf: true,
          leftNodeid: -1,
          missingDir: 1,
          rightNodeid: -1,
          sitename: 'guest',
          weight: 0.7671721303,
        },
      ],
    },
    {
      missingDirMaskdict: {},
      splitMaskdict: {},
      tree: [
        {
          bid: 0.01490308034690498,
          fid: 18,
          id: 0,
          isLeaf: false,
          leftNodeid: 1,
          missingDir: 1,
          rightNodeid: 2,
          sitename: 'guest',
          weight: -0.6261593439,
        },
        {
          bid: 0.138904674809873,
          fid: 20,
          id: 1,
          isLeaf: false,
          leftNodeid: 3,
          missingDir: 1,
          rightNodeid: 4,
          sitename: 'guest',
          weight: -0.843946867,
        },
        {
          bid: -0.7231682691788779,
          fid: 19,
          id: 2,
          isLeaf: false,
          leftNodeid: 5,
          missingDir: 1,
          rightNodeid: 6,
          sitename: 'guest',
          weight: 0.0273470721,
        },
        {
          bid: -0.237695039685139,
          fid: 7,
          id: 3,
          isLeaf: false,
          leftNodeid: 7,
          missingDir: 1,
          rightNodeid: 8,
          sitename: 'guest',
          weight: -0.8857719146,
        },
        {
          bid: -0.247824705203846,
          fid: 10,
          id: 4,
          isLeaf: false,
          leftNodeid: 9,
          missingDir: 1,
          rightNodeid: 10,
          sitename: 'guest',
          weight: -0.182604961,
        },
        {
          bid: -0.3080629989550904,
          fid: 10,
          id: 5,
          isLeaf: false,
          leftNodeid: 11,
          missingDir: 1,
          rightNodeid: 12,
          sitename: 'guest',
          weight: -0.5001783626,
        },
        {
          bid: 0.9047122646969068,
          fid: 18,
          id: 6,
          isLeaf: false,
          leftNodeid: 13,
          missingDir: 1,
          rightNodeid: 14,
          sitename: 'guest',
          weight: 0.2214897652,
        },
        {
          bid: 0.0,
          fid: 0,
          id: 7,
          isLeaf: true,
          leftNodeid: -1,
          missingDir: 1,
          rightNodeid: -1,
          sitename: 'guest',
          weight: -0.6924350903,
        },
        {
          bid: 0.0,
          fid: 0,
          id: 8,
          isLeaf: true,
          leftNodeid: -1,
          missingDir: 1,
          rightNodeid: -1,
          sitename: 'guest',
          weight: -0.9869260199,
        },
        {
          bid: 0.0,
          fid: 0,
          id: 9,
          isLeaf: true,
          leftNodeid: -1,
          missingDir: 1,
          rightNodeid: -1,
          sitename: 'guest',
          weight: 0.1239539843,
        },
        {
          bid: 0.0,
          fid: 0,
          id: 10,
          isLeaf: true,
          leftNodeid: -1,
          missingDir: 1,
          rightNodeid: -1,
          sitename: 'guest',
          weight: -0.4603918454,
        },
        {
          bid: 0.0,
          fid: 0,
          id: 11,
          isLeaf: true,
          leftNodeid: -1,
          missingDir: 1,
          rightNodeid: -1,
          sitename: 'guest',
          weight: -0.1965495968,
        },
        {
          bid: 0.0,
          fid: 0,
          id: 12,
          isLeaf: true,
          leftNodeid: -1,
          missingDir: 1,
          rightNodeid: -1,
          sitename: 'guest',
          weight: -0.9676584514,
        },
        {
          bid: 0.0,
          fid: 0,
          id: 13,
          isLeaf: true,
          leftNodeid: -1,
          missingDir: 1,
          rightNodeid: -1,
          sitename: 'guest',
          weight: -0.0601500899,
        },
        {
          bid: 0.0,
          fid: 0,
          id: 14,
          isLeaf: true,
          leftNodeid: -1,
          missingDir: 1,
          rightNodeid: -1,
          sitename: 'guest',
          weight: 0.4042842294,
        },
      ],
    },
  ],
  meta: {
    meta_data: {
      learningRate: 0.3,
      nIterNoChange: true,
      numTrees: 3,
      objectiveMeta: {
        objective: 'cross_entropy',
        param: [],
      },
      quantileMeta: {
        binNum: 32,
        quantileMethod: '',
      },
      taskType: 'classification',
      tol: 0.0001,
      treeMeta: {
        criterionMeta: {
          criterionMethod: 'xgboost',
          criterionParam: [0.1, 0.0],
        },
        maxDepth: 3,
        minImpuritySplit: 0.001,
        minLeafNode: 1,
        minSampleSplit: 2,
        useMissing: false,
        zeroAsMissing: false,
      },
      useMissing: false,
      workMode: '',
      zeroAsMissing: false,
    },
    module_name: 'HomoSecureboost',
  },
}
